<?xml version="1.0" encoding="UTF-8"?>
<package version="2.1" xmlns="http://pear.php.net/dtd/package-2.1" xmlns:tasks="http://pear.php.net/dtd/tasks-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/dtd/tasks-1.0     http://pear.php.net/dtd/tasks-1.0.xsd     http://pear.php.net/dtd/package-2.1     http://pear.php.net/dtd/package-2.1.xsd">
 <name>PEAR2_Exception</name>
 <channel>pear2.php.net</channel>
 <summary>PEAR2\Exception is the standard exception class for PEAR2.
</summary>
 <description>In addition to supporting the default signature of the built-in
Exception class, PEAR2\Exception also supports passing a
cause of an exception, which can be another exception object
or a PEAR2_MultiErrors object.  The error messages of the causes
are used when constructing the error message displayed when
converting PEAR2\Exception to a string.

PEAR2\Exception should always be extended by your own custom exception
class for the package.</description>
 <lead>
  <name>Gregory Beaver</name>
  <user>cellog</user>
  <email>cellog@php.net</email>
  <active>yes</active>
 </lead>
 <lead>
  <name>Tomas V.V. Cox</name>
  <user>cox</user>
  <email>cox@idecnet.com</email>
  <active>no</active>
 </lead>
 <lead>
  <name>Bertrand Mansion</name>
  <user>mansion</user>
  <email>bmansion@mamasam.com</email>
  <active>no</active>
 </lead>
 <developer>
  <name>Hans Lellelid</name>
  <user>hlellelid</user>
  <email>hans@velum.net</email>
  <active>no</active>
 </developer>
 <date>2011-07-13</date>
 <time>10:49:07</time>
 <version>
  <release>0.3.0</release>
  <api>0.1.0</api>
 </version>
 <stability>
  <release>alpha</release>
  <api>alpha</api>
 </stability>
 <license uri="http://www.opensource.org/licenses/bsd-license.php">New BSD License</license>
 <notes>- Removed addObserver() / removeObserver() as people can achieve that
  with their own observer function / classes via set_exception_handler
- Removed getTraceSafe() as it was falling back on debug_backtrace()
  when getTrace() was empty, which only happens when an Exception is
  thrown outside of a class/function scope.</notes>
 <contents>
  <dir name="/">
   <dir name="src" baseinstalldir="/">
    <dir name="PEAR2">
     <file role="php" name="Exception.php"/>
    </dir>
   </dir>
  </dir>
 </contents>
 <dependencies>
  <required>
   <php>
    <min>5.2.0</min>
   </php>
   <pearinstaller>
    <min>2.0.0a1</min>
   </pearinstaller>
  </required>
 </dependencies>
 <phprelease/>
</package>
